<?php 
$error000 = "false";
$error001 = "SITE DESATIVADO POR MOTIVO DE TESTE - COD. 001";
$error002 = "APIKEY EXPIRADA, AGUARDANDO NOVA KEY DE ACESSO - COD. 002";
$error003 = "NOME DE INVOCARDOR INVALIDO, VERIFIQUE A GRAFIA DO NOME E A REGIÃO DESEJADA - COD. 003";
$error004 = "POR ALGUM MOTIVO NÃO PODEMOS ACESSAR OS DADOS REQUERIDOS, ESTAMOS TRABALHANDO CONSERTAR ESTE ERROR - COD. 004";
$error005 = "A CONEXÃO COM O BANCO DE DADOS NÃO FOI POSSIVEL - COD. 005";
?>